name: gellohabits
description: Un tracker de hábitos con sistema de rewards basados en la evolución de un personaje animado.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  sembast: ^2.4.9
  cupertino_icons: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/characters/Base – Purple.png
